#include "display/calib_pose_icons.h"
#include <string.h>

// Use bitmaps defined in header file

static const uint8_t* pose_icon_bitmaps[CALIB_POSE_COUNT] = {
    icon_rotate, icon_xp, icon_xn, icon_yp, icon_yn, icon_zp, icon_zn, icon_holdstill, icon_xr, icon_yr, icon_zr, icon_fr, icon_comp
};

// Draw a 48x48 icon bitmap at (x, y)
static void draw_icon_bitmap(ssd1306_handle_t* disp, int x, int y, const uint8_t* bitmap) {
    for (int row = 0; row < CALIB_ICON_SIZE; ++row) {
        for (int col = 0; col < CALIB_ICON_SIZE; ++col) {
            int byte_idx = row * 6 + (col / 8);
            int bit_idx = 7 - (col % 8);
            if (bitmap[byte_idx] & (1 << bit_idx)) {
                ssd1306_draw_pixel(disp, x + col, y + row, 1);
            }
        }
    }
}

void draw_calib_pose_icon(ssd1306_handle_t* disp, int x, int y, calib_pose_icon_t pose) {
    if (pose >= 0 && pose < CALIB_POSE_COUNT) {
        draw_icon_bitmap(disp, x, y, pose_icon_bitmaps[pose]);
    }
}


// NOTE: The actual .inl files should contain 288 bytes each, generated by a bitmap editor or script. These are placeholders for clarity.
